//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorTarea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjuntos
    {
        public int IdAdjunto { get; set; }
        public int IdTarea { get; set; }
        public string NombreArchivo { get; set; }
        public string RutaArchivo { get; set; }
        public System.DateTime FechaSubida { get; set; }
    
        public virtual Tareas Tareas { get; set; }
    }
}
