//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorTarea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitaciones
    {
        public int IdInvitacion { get; set; }
        public int IdProyecto { get; set; }
        public string Email { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaEnvio { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
    }
}
